version: "3.8"

services:

  # PostgreSQL
  postgres:
    container_name: java-postgres
    image: postgres:latest
    ports:
      - "5433:5432"
    env_file:
      - docker/postgres/env/postgres.dev.env
    volumes:
#      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  # My-test
  my-test:
    build: ./
    container_name: java-app
    ports:
      - "8089:8089"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres