server:
  port: 8089
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:${DATABASE_URL:postgresql://localhost:5432/mytest}
    username: ${USER_DB:postgres}
    driverClassName: org.postgresql.Driver


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
#        default_schema: ${SCHEMA_DB:post}
      open-in-view: false

