drop table if exists message cascade;
drop table if exists users cascade;

create table if not exists message (
                         id int8 generated by default as identity,
                         message varchar(255) not null,
                         time_created int8 not null,
                         username varchar(255) not null,
                         primary key (id)
);

create table if not exists users (
                       id int8 generated by default as identity,
                       password varchar(255) not null,
                       username varchar(255) not null,
                       primary key (id)
);

insert into users (password, username) values ('$2a$10$2Lb0nmXJO/HqFh/gB8S3yehUjTcA4PhRN6vcosevNEewLok7nEtnO', 'user');

insert into message (message, time_created, username) values ('Test Message 1', '1659557307667', 'user');
insert into message (message, time_created, username) values ('Test Message 2', '1659557661053', 'user');
insert into message (message, time_created, username) values ('Test Message 3', '1659557661885', 'user');
insert into message (message, time_created, username) values ('Test Message 4', '1659557662708', 'user');
insert into message (message, time_created, username) values ('Test Message 5', '1659557663605', 'user');
insert into message (message, time_created, username) values ('Test Message 6', '1659557664605', 'user');
insert into message (message, time_created, username) values ('Test Message 7', '1659557665605', 'user');
insert into message (message, time_created, username) values ('Test Message 8', '1659557666605', 'user');
insert into message (message, time_created, username) values ('Test Message 9', '1659557667605', 'user');
insert into message (message, time_created, username) values ('Test Message 10', '1659557668605', 'user');